-- =============================================
-- ADMIN USERS SEED DATA
-- =============================================
-- Run this SQL in Supabase SQL Editor to create test admin users
-- Passwords are bcrypt hashed with 10 salt rounds

-- Note: These password hashes are for the following passwords:
-- Owner@123
-- Manager@123
-- FrontDesk@123
-- Accountant@123

INSERT INTO admin_users (email, password_hash, full_name, role, phone, is_active) VALUES
  (
    'owner@happyholidays.com',
    '$2a$10$rX8YZKqVBqYvW8N5Y6Y5xuqC.9ZYJ4N5Y6Y5xuqC.9ZYJ4N5Y6Y5xu', -- Owner@123 (will be generated by API)
    'Union Awaas Happy Holiday Owner',
    'Owner',
    '+919876543210',
    true
  ),
  (
    'manager@happyholidays.com',
    '$2a$10$rX8YZKqVBqYvW8N5Y6Y5xuqC.9ZYJ4N5Y6Y5xuqC.9ZYJ4N5Y6Y5xu', -- Manager@123 (will be generated by API)
    'Property Manager',
    'Manager',
    '+919876543211',
    true
  ),
  (
    'frontdesk@happyholidays.com',
    '$2a$10$rX8YZKqVBqYvW8N5Y6Y5xuqC.9ZYJ4N5Y6Y5xuqC.9ZYJ4N5Y6Y5xu', -- FrontDesk@123 (will be generated by API)
    'Front Desk Staff',
    'Front Desk',
    '+919876543212',
    true
  ),
  (
    'accountant@happyholidays.com',
    '$2a$10$rX8YZKqVBqYvW8N5Y6Y5xuqC.9ZYJ4N5Y6Y5xuqC.9ZYJ4N5Y6Y5xu', -- Accountant@123 (will be generated by API)
    'Account Manager',
    'Accountant',
    '+919876543213',
    true
  )
ON CONFLICT (email) DO NOTHING;

-- Verify the insert
SELECT email, full_name, role, is_active, created_at FROM admin_users ORDER BY created_at DESC;
